package com.hibernate.Entity;

import javax.persistence.Entity;
import javax.persistence.Id;

// Generated 16 Jul, 2021 4:52:21 PM by Hibernate Tools 5.4.14.Final

/**
 * Civil generated by hbm2java
 */
@Entity
public class Civil implements java.io.Serializable {
   @Id
	private Integer id;
	private String name;
	private String address;
	private String city;
	private String sallary;
	private String job;
	private String department;
	private String depIdl;

	public Civil() {
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getAddress() {
		return this.address;
	}

	public void setAddress(String address) {
		this.address = address;
	}

	public String getCity() {
		return this.city;
	}

	public void setCity(String city) {
		this.city = city;
	}

	public String getSallary() {
		return this.sallary;
	}

	public void setSallary(String sallary) {
		this.sallary = sallary;
	}

	public String getJob() {
		return this.job;
	}

	public void setJob(String job) {
		this.job = job;
	}

	public String getDepartment() {
		return this.department;
	}

	public void setDepartment(String department) {
		this.department = department;
	}

	public String getDepIdl() {
		return this.depIdl;
	}

	public void setDepIdl(String depIdl) {
		this.depIdl = depIdl;
	}

}
